AppBundle\Entity\EstadoActividad:
    type: entity
    table: estado_actividad
    uniqueConstraints:
        estado_actividad_pk:
            columns:
                - id_estado_actividad
    id:
        idEstadoActividad:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_estado_actividad
            generator:
                strategy: SEQUENCE
    fields:
        nomEstadoActividad:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: nom_estado_actividad
        descripcionEstadoActividad:
            type: string
            nullable: false
            length: 250
            fixed: false
            column: descripcion_estado_actividad
    lifecycleCallbacks: {  }
