AppBundle\Entity\TipoCiclo:
    type: entity
    table: tipo_ciclo
    uniqueConstraints:
        tipo_ciclo_pk:
            columns:
                - id_tipo_ciclo
    id:
        idTipoCiclo:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_tipo_ciclo
            generator:
                strategy: SEQUENCE
    fields:
        nomTipoCiclo:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: nom_tipo_ciclo
    lifecycleCallbacks: {  }
